/*
 * ATM Locations API
 * ATM Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.atms.client;

import com.mastercard.api.atms.ApiCallback;
import com.mastercard.api.atms.ApiClient;
import com.mastercard.api.atms.ApiException;
import com.mastercard.api.atms.ApiResponse;
import com.mastercard.api.atms.Configuration;
import com.mastercard.api.atms.Pair;
import com.mastercard.api.atms.ProgressRequestBody;
import com.mastercard.api.atms.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mastercard.api.atms.model.AtmSearch;
import com.mastercard.api.atms.model.Atms;
import com.mastercard.api.atms.model.ErrorResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AtmsApi {
    private ApiClient localVarApiClient;

    public AtmsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AtmsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for getAtms
     * @param atmSearch A JSON object containing item data (required)
     * @param limit The number of items to be retrieved (optional)
     * @param offset The page offset used for the query (optional)
     * @param distance Distance measurement for calculating the radius search. Optional The length of distance from the centroid point. Value string(&lt;25). The default will be 5 units (optional)
     * @param distanceUnit Unit of measurement for calculating the radius search. Optional. Measurement of distance unit in miles or kilometers. Value string (MILE or KM) (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of ATM details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAtmsCall(AtmSearch atmSearch, Integer limit, Integer offset, Integer distance, String distanceUnit, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = atmSearch;

        // create path and map variables
        String localVarPath = "/searches";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (distance != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("distance", distance));
        }

        if (distanceUnit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("distance_unit", distanceUnit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAtmsValidateBeforeCall(AtmSearch atmSearch, Integer limit, Integer offset, Integer distance, String distanceUnit, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'atmSearch' is set
        if (atmSearch == null) {
            throw new ApiException("Missing the required parameter 'atmSearch' when calling getAtms(Async)");
        }
        

        okhttp3.Call localVarCall = getAtmsCall(atmSearch, limit, offset, distance, distanceUnit, _callback);
        return localVarCall;

    }

    /**
     * Get a list of ATM details
     * Returns detailed information on ATMs based on the provided query parameters
     * @param atmSearch A JSON object containing item data (required)
     * @param limit The number of items to be retrieved (optional)
     * @param offset The page offset used for the query (optional)
     * @param distance Distance measurement for calculating the radius search. Optional The length of distance from the centroid point. Value string(&lt;25). The default will be 5 units (optional)
     * @param distanceUnit Unit of measurement for calculating the radius search. Optional. Measurement of distance unit in miles or kilometers. Value string (MILE or KM) (optional)
     * @return Atms
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of ATM details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public Atms getAtms(AtmSearch atmSearch, Integer limit, Integer offset, Integer distance, String distanceUnit) throws ApiException {
        ApiResponse<Atms> localVarResp = getAtmsWithHttpInfo(atmSearch, limit, offset, distance, distanceUnit);
        return localVarResp.getData();
    }

    /**
     * Get a list of ATM details
     * Returns detailed information on ATMs based on the provided query parameters
     * @param atmSearch A JSON object containing item data (required)
     * @param limit The number of items to be retrieved (optional)
     * @param offset The page offset used for the query (optional)
     * @param distance Distance measurement for calculating the radius search. Optional The length of distance from the centroid point. Value string(&lt;25). The default will be 5 units (optional)
     * @param distanceUnit Unit of measurement for calculating the radius search. Optional. Measurement of distance unit in miles or kilometers. Value string (MILE or KM) (optional)
     * @return ApiResponse&lt;Atms&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of ATM details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Atms> getAtmsWithHttpInfo(AtmSearch atmSearch, Integer limit, Integer offset, Integer distance, String distanceUnit) throws ApiException {
        okhttp3.Call localVarCall = getAtmsValidateBeforeCall(atmSearch, limit, offset, distance, distanceUnit, null);
        Type localVarReturnType = new TypeToken<Atms>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a list of ATM details (asynchronously)
     * Returns detailed information on ATMs based on the provided query parameters
     * @param atmSearch A JSON object containing item data (required)
     * @param limit The number of items to be retrieved (optional)
     * @param offset The page offset used for the query (optional)
     * @param distance Distance measurement for calculating the radius search. Optional The length of distance from the centroid point. Value string(&lt;25). The default will be 5 units (optional)
     * @param distanceUnit Unit of measurement for calculating the radius search. Optional. Measurement of distance unit in miles or kilometers. Value string (MILE or KM) (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of ATM details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAtmsAsync(AtmSearch atmSearch, Integer limit, Integer offset, Integer distance, String distanceUnit, final ApiCallback<Atms> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAtmsValidateBeforeCall(atmSearch, limit, offset, distance, distanceUnit, _callback);
        Type localVarReturnType = new TypeToken<Atms>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
