/*
 * ATM Locations API
 * ATM Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.atms.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Atm
 */
public class AtmTest {
    private final Atm model = new Atm();

    /**
     * Model tests for Atm
     */
    @Test
    public void testAtm() {
        // TODO: test Atm
    }

    /**
     * Test the property 'accessFees'
     */
    @Test
    public void accessFeesTest() {
        // TODO: test accessFees
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'airportCode'
     */
    @Test
    public void airportCodeTest() {
        // TODO: test airportCode
    }

    /**
     * Test the property 'atmTerminalId'
     */
    @Test
    public void atmTerminalIdTest() {
        // TODO: test atmTerminalId
    }

    /**
     * Test the property 'availability'
     */
    @Test
    public void availabilityTest() {
        // TODO: test availability
    }

    /**
     * Test the property 'camera'
     */
    @Test
    public void cameraTest() {
        // TODO: test camera
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'countryName'
     */
    @Test
    public void countryNameTest() {
        // TODO: test countryName
    }

    /**
     * Test the property 'countrySubdivisionCode'
     */
    @Test
    public void countrySubdivisionCodeTest() {
        // TODO: test countrySubdivisionCode
    }

    /**
     * Test the property 'countrySubdivisionName'
     */
    @Test
    public void countrySubdivisionNameTest() {
        // TODO: test countrySubdivisionName
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'distanceUnit'
     */
    @Test
    public void distanceUnitTest() {
        // TODO: test distanceUnit
    }

    /**
     * Test the property 'geocodingResult'
     */
    @Test
    public void geocodingResultTest() {
        // TODO: test geocodingResult
    }

    /**
     * Test the property 'handicapAccessible'
     */
    @Test
    public void handicapAccessibleTest() {
        // TODO: test handicapAccessible
    }

    /**
     * Test the property 'hasSharedDeposit'
     */
    @Test
    public void hasSharedDepositTest() {
        // TODO: test hasSharedDeposit
    }

    /**
     * Test the property 'isSurchargeFreeAlliance'
     */
    @Test
    public void isSurchargeFreeAllianceTest() {
        // TODO: test isSurchargeFreeAlliance
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'locationName'
     */
    @Test
    public void locationNameTest() {
        // TODO: test locationName
    }

    /**
     * Test the property 'locationType'
     */
    @Test
    public void locationTypeTest() {
        // TODO: test locationType
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'ownerICA'
     */
    @Test
    public void ownerICATest() {
        // TODO: test ownerICA
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'routeTransactionNumber'
     */
    @Test
    public void routeTransactionNumberTest() {
        // TODO: test routeTransactionNumber
    }

    /**
     * Test the property 'sponsor'
     */
    @Test
    public void sponsorTest() {
        // TODO: test sponsor
    }

    /**
     * Test the property 'sponsorICA'
     */
    @Test
    public void sponsorICATest() {
        // TODO: test sponsorICA
    }

    /**
     * Test the property 'supportsEmv'
     */
    @Test
    public void supportsEmvTest() {
        // TODO: test supportsEmv
    }

    /**
     * Test the property 'surchargeFreeAllianceNetwork'
     */
    @Test
    public void surchargeFreeAllianceNetworkTest() {
        // TODO: test surchargeFreeAllianceNetwork
    }

}
