/*
 * ATM Locations API
 * ATM Locations API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.atms.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ATM detail information
 */
@ApiModel(description = "ATM detail information")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-02T08:45:21.825725200-05:00[America/Chicago]")
public class Atm {
  public static final String SERIALIZED_NAME_ACCESS_FEES = "accessFees";
  @SerializedName(SERIALIZED_NAME_ACCESS_FEES)
  private String accessFees;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "addressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "addressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  private String addressLine2;

  public static final String SERIALIZED_NAME_AIRPORT_CODE = "airportCode";
  @SerializedName(SERIALIZED_NAME_AIRPORT_CODE)
  private String airportCode;

  public static final String SERIALIZED_NAME_ATM_TERMINAL_ID = "atmTerminalId";
  @SerializedName(SERIALIZED_NAME_ATM_TERMINAL_ID)
  private String atmTerminalId;

  public static final String SERIALIZED_NAME_AVAILABILITY = "availability";
  @SerializedName(SERIALIZED_NAME_AVAILABILITY)
  private String availability;

  public static final String SERIALIZED_NAME_CAMERA = "camera";
  @SerializedName(SERIALIZED_NAME_CAMERA)
  private String camera;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_COUNTRY_NAME = "countryName";
  @SerializedName(SERIALIZED_NAME_COUNTRY_NAME)
  private String countryName;

  public static final String SERIALIZED_NAME_COUNTRY_SUBDIVISION_CODE = "countrySubdivisionCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_SUBDIVISION_CODE)
  private String countrySubdivisionCode;

  public static final String SERIALIZED_NAME_COUNTRY_SUBDIVISION_NAME = "countrySubdivisionName";
  @SerializedName(SERIALIZED_NAME_COUNTRY_SUBDIVISION_NAME)
  private String countrySubdivisionName;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_DISTANCE = "distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  private Double distance;

  public static final String SERIALIZED_NAME_DISTANCE_UNIT = "distanceUnit";
  @SerializedName(SERIALIZED_NAME_DISTANCE_UNIT)
  private String distanceUnit;

  public static final String SERIALIZED_NAME_GEOCODING_RESULT = "geocodingResult";
  @SerializedName(SERIALIZED_NAME_GEOCODING_RESULT)
  private String geocodingResult;

  public static final String SERIALIZED_NAME_HANDICAP_ACCESSIBLE = "handicapAccessible";
  @SerializedName(SERIALIZED_NAME_HANDICAP_ACCESSIBLE)
  private String handicapAccessible;

  public static final String SERIALIZED_NAME_HAS_SHARED_DEPOSIT = "hasSharedDeposit";
  @SerializedName(SERIALIZED_NAME_HAS_SHARED_DEPOSIT)
  private String hasSharedDeposit;

  public static final String SERIALIZED_NAME_IS_SURCHARGE_FREE_ALLIANCE = "isSurchargeFreeAlliance";
  @SerializedName(SERIALIZED_NAME_IS_SURCHARGE_FREE_ALLIANCE)
  private String isSurchargeFreeAlliance;

  public static final String SERIALIZED_NAME_LATITUDE = "latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private String latitude;

  public static final String SERIALIZED_NAME_LOCATION_NAME = "locationName";
  @SerializedName(SERIALIZED_NAME_LOCATION_NAME)
  private String locationName;

  public static final String SERIALIZED_NAME_LOCATION_TYPE = "locationType";
  @SerializedName(SERIALIZED_NAME_LOCATION_TYPE)
  private String locationType;

  public static final String SERIALIZED_NAME_LONGITUDE = "longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private String longitude;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private String owner;

  public static final String SERIALIZED_NAME_OWNER_I_C_A = "ownerICA";
  @SerializedName(SERIALIZED_NAME_OWNER_I_C_A)
  private String ownerICA;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_ROUTE_TRANSACTION_NUMBER = "routeTransactionNumber";
  @SerializedName(SERIALIZED_NAME_ROUTE_TRANSACTION_NUMBER)
  private String routeTransactionNumber;

  public static final String SERIALIZED_NAME_SPONSOR = "sponsor";
  @SerializedName(SERIALIZED_NAME_SPONSOR)
  private String sponsor;

  public static final String SERIALIZED_NAME_SPONSOR_I_C_A = "sponsorICA";
  @SerializedName(SERIALIZED_NAME_SPONSOR_I_C_A)
  private String sponsorICA;

  public static final String SERIALIZED_NAME_SUPPORTS_EMV = "supportsEmv";
  @SerializedName(SERIALIZED_NAME_SUPPORTS_EMV)
  private String supportsEmv;

  public static final String SERIALIZED_NAME_SURCHARGE_FREE_ALLIANCE_NETWORK = "surchargeFreeAllianceNetwork";
  @SerializedName(SERIALIZED_NAME_SURCHARGE_FREE_ALLIANCE_NETWORK)
  private String surchargeFreeAllianceNetwork;


  public Atm accessFees(String accessFees) {
    
    this.accessFees = accessFees;
    return this;
  }

   /**
   * This value indicates under what conditions access fees are charged. Options are UNKNOWN, DOMESTIC, INTERNATIONAL, DOMESTIC_AND_INTERNATIONAL, NO_FEE.
   * @return accessFees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DOMESTIC", value = "This value indicates under what conditions access fees are charged. Options are UNKNOWN, DOMESTIC, INTERNATIONAL, DOMESTIC_AND_INTERNATIONAL, NO_FEE.")

  public String getAccessFees() {
    return accessFees;
  }


  public void setAccessFees(String accessFees) {
    this.accessFees = accessFees;
  }


  public Atm addressLine1(String addressLine1) {
    
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Line 1 of the street address for the ATM location. Usually includes the street number and name.
   * @return addressLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1 Oak Street", value = "Line 1 of the street address for the ATM location. Usually includes the street number and name.")

  public String getAddressLine1() {
    return addressLine1;
  }


  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public Atm addressLine2(String addressLine2) {
    
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * Line 2 of the street address usually an apartment number or suite number.
   * @return addressLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Apt 1", value = "Line 2 of the street address usually an apartment number or suite number.")

  public String getAddressLine2() {
    return addressLine2;
  }


  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public Atm airportCode(String airportCode) {
    
    this.airportCode = airportCode;
    return this;
  }

   /**
   * The Airport Code
   * @return airportCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "STL", value = "The Airport Code")

  public String getAirportCode() {
    return airportCode;
  }


  public void setAirportCode(String airportCode) {
    this.airportCode = airportCode;
  }


  public Atm atmTerminalId(String atmTerminalId) {
    
    this.atmTerminalId = atmTerminalId;
    return this;
  }

   /**
   * The ATM Terminal Id
   * @return atmTerminalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "NH044143", value = "The ATM Terminal Id")

  public String getAtmTerminalId() {
    return atmTerminalId;
  }


  public void setAtmTerminalId(String atmTerminalId) {
    this.atmTerminalId = atmTerminalId;
  }


  public Atm availability(String availability) {
    
    this.availability = availability;
    return this;
  }

   /**
   * This value indicates the availability hours of the ATM. Options are UNKNOWN, ALWAYS_AVAILABLE, BUSINESS_HOURS, IRREGULAR_HOURS.
   * @return availability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "BUSINESS_HOURS", value = "This value indicates the availability hours of the ATM. Options are UNKNOWN, ALWAYS_AVAILABLE, BUSINESS_HOURS, IRREGULAR_HOURS.")

  public String getAvailability() {
    return availability;
  }


  public void setAvailability(String availability) {
    this.availability = availability;
  }


  public Atm camera(String camera) {
    
    this.camera = camera;
    return this;
  }

   /**
   * This value indicates whether or not a security camera is present or near ATM
   * @return camera
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "NO", value = "This value indicates whether or not a security camera is present or near ATM")

  public String getCamera() {
    return camera;
  }


  public void setCamera(String camera) {
    this.camera = camera;
  }


  public Atm countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Three digit alpha country code as defined in ISO
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "USA", value = "Three digit alpha country code as defined in ISO")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public Atm countryName(String countryName) {
    
    this.countryName = countryName;
    return this;
  }

   /**
   * Name of the country.
   * @return countryName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "United States", value = "Name of the country.")

  public String getCountryName() {
    return countryName;
  }


  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }


  public Atm countrySubdivisionCode(String countrySubdivisionCode) {
    
    this.countrySubdivisionCode = countrySubdivisionCode;
    return this;
  }

   /**
   * Code of the state or province for an ATM location.
   * @return countrySubdivisionCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "MO", value = "Code of the state or province for an ATM location.")

  public String getCountrySubdivisionCode() {
    return countrySubdivisionCode;
  }


  public void setCountrySubdivisionCode(String countrySubdivisionCode) {
    this.countrySubdivisionCode = countrySubdivisionCode;
  }


  public Atm countrySubdivisionName(String countrySubdivisionName) {
    
    this.countrySubdivisionName = countrySubdivisionName;
    return this;
  }

   /**
   * Name of the state or province for an ATM location.
   * @return countrySubdivisionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Missouri", value = "Name of the state or province for an ATM location.")

  public String getCountrySubdivisionName() {
    return countrySubdivisionName;
  }


  public void setCountrySubdivisionName(String countrySubdivisionName) {
    this.countrySubdivisionName = countrySubdivisionName;
  }


  public Atm city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * The name of the city for an ATM location.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "OFallon", value = "The name of the city for an ATM location.")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public Atm distance(Double distance) {
    
    this.distance = distance;
    return this;
  }

   /**
   * This is the numerical value for the distance from the provided location to the selected ATM.
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.75723000000001", value = "This is the numerical value for the distance from the provided location to the selected ATM.")

  public Double getDistance() {
    return distance;
  }


  public void setDistance(Double distance) {
    this.distance = distance;
  }


  public Atm distanceUnit(String distanceUnit) {
    
    this.distanceUnit = distanceUnit;
    return this;
  }

   /**
   * This is the unit of measure value for the distance from the provided location to the selected ATM. Options are KM and MILE.
   * @return distanceUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "MILE", value = "This is the unit of measure value for the distance from the provided location to the selected ATM. Options are KM and MILE.")

  public String getDistanceUnit() {
    return distanceUnit;
  }


  public void setDistanceUnit(String distanceUnit) {
    this.distanceUnit = distanceUnit;
  }


  public Atm geocodingResult(String geocodingResult) {
    
    this.geocodingResult = geocodingResult;
    return this;
  }

   /**
   * GeocodingResult for the ATM
   * @return geocodingResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "G3", value = "GeocodingResult for the ATM")

  public String getGeocodingResult() {
    return geocodingResult;
  }


  public void setGeocodingResult(String geocodingResult) {
    this.geocodingResult = geocodingResult;
  }


  public Atm handicapAccessible(String handicapAccessible) {
    
    this.handicapAccessible = handicapAccessible;
    return this;
  }

   /**
   * This indicates whether the ATM has the ability to read chip cards or not. Options are UNKNOWN, IS_HANDICAP_ACCESSIBLE, NOT_HANDICAP_ACCESSIBLE.
   * @return handicapAccessible
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "IS_HANDICAP_ACCESSIBLE", value = "This indicates whether the ATM has the ability to read chip cards or not. Options are UNKNOWN, IS_HANDICAP_ACCESSIBLE, NOT_HANDICAP_ACCESSIBLE.")

  public String getHandicapAccessible() {
    return handicapAccessible;
  }


  public void setHandicapAccessible(String handicapAccessible) {
    this.handicapAccessible = handicapAccessible;
  }


  public Atm hasSharedDeposit(String hasSharedDeposit) {
    
    this.hasSharedDeposit = hasSharedDeposit;
    return this;
  }

   /**
   * This value indicates whether or not the ATM participates in the MasterCard Shared Deposit network. Options are YES or NO.
   * @return hasSharedDeposit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "YES", value = "This value indicates whether or not the ATM participates in the MasterCard Shared Deposit network. Options are YES or NO.")

  public String getHasSharedDeposit() {
    return hasSharedDeposit;
  }


  public void setHasSharedDeposit(String hasSharedDeposit) {
    this.hasSharedDeposit = hasSharedDeposit;
  }


  public Atm isSurchargeFreeAlliance(String isSurchargeFreeAlliance) {
    
    this.isSurchargeFreeAlliance = isSurchargeFreeAlliance;
    return this;
  }

   /**
   * This value indicates whether or not the ATM participates in the MasterCard Shared (only) Surcharge Free Alliance network. Options are YES or NO.
   * @return isSurchargeFreeAlliance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "YES", value = "This value indicates whether or not the ATM participates in the MasterCard Shared (only) Surcharge Free Alliance network. Options are YES or NO.")

  public String getIsSurchargeFreeAlliance() {
    return isSurchargeFreeAlliance;
  }


  public void setIsSurchargeFreeAlliance(String isSurchargeFreeAlliance) {
    this.isSurchargeFreeAlliance = isSurchargeFreeAlliance;
  }


  public Atm latitude(String latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * The latitude of the ATM
   * @return latitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "38.670337", value = "The latitude of the ATM")

  public String getLatitude() {
    return latitude;
  }


  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  public Atm locationName(String locationName) {
    
    this.locationName = locationName;
    return this;
  }

   /**
   * The name of the ATM location
   * @return locationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "That Bank", value = "The name of the ATM location")

  public String getLocationName() {
    return locationName;
  }


  public void setLocationName(String locationName) {
    this.locationName = locationName;
  }


  public Atm locationType(String locationType) {
    
    this.locationType = locationType;
    return this;
  }

   /**
   * Type of location for the ATM. Options are OTHER, AIRPORT, HOSPITAL, FINANCIAL_INSTITUTION.
   * @return locationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FINANCIAL_INSTITUTION", value = "Type of location for the ATM. Options are OTHER, AIRPORT, HOSPITAL, FINANCIAL_INSTITUTION.")

  public String getLocationType() {
    return locationType;
  }


  public void setLocationType(String locationType) {
    this.locationType = locationType;
  }


  public Atm longitude(String longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * The longitude of the ATM.
   * @return longitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "-90.443727", value = "The longitude of the ATM.")

  public String getLongitude() {
    return longitude;
  }


  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  public Atm owner(String owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * This is the DBA name of the financial institution affiliate or independent service organization.
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "That Bank LLC", value = "This is the DBA name of the financial institution affiliate or independent service organization.")

  public String getOwner() {
    return owner;
  }


  public void setOwner(String owner) {
    this.owner = owner;
  }


  public Atm ownerICA(String ownerICA) {
    
    this.ownerICA = ownerICA;
    return this;
  }

   /**
   * This is the ICA of the entity that owns the ATM
   * @return ownerICA
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9386", value = "This is the ICA of the entity that owns the ATM")

  public String getOwnerICA() {
    return ownerICA;
  }


  public void setOwnerICA(String ownerICA) {
    this.ownerICA = ownerICA;
  }


  public Atm postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The postal code of the ATM location.
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "63366", value = "The postal code of the ATM location.")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public Atm routeTransactionNumber(String routeTransactionNumber) {
    
    this.routeTransactionNumber = routeTransactionNumber;
    return this;
  }

   /**
   * The routing transaction number
   * @return routeTransactionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "840180546", value = "The routing transaction number")

  public String getRouteTransactionNumber() {
    return routeTransactionNumber;
  }


  public void setRouteTransactionNumber(String routeTransactionNumber) {
    this.routeTransactionNumber = routeTransactionNumber;
  }


  public Atm sponsor(String sponsor) {
    
    this.sponsor = sponsor;
    return this;
  }

   /**
   * This is the legal or business name of the entity that sponsors the owner of the ATM into the MasterCard network.
   * @return sponsor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "That Bank LLC", value = "This is the legal or business name of the entity that sponsors the owner of the ATM into the MasterCard network.")

  public String getSponsor() {
    return sponsor;
  }


  public void setSponsor(String sponsor) {
    this.sponsor = sponsor;
  }


  public Atm sponsorICA(String sponsorICA) {
    
    this.sponsorICA = sponsorICA;
    return this;
  }

   /**
   * This is the ICA of entity that sponsors the owner of the ATM
   * @return sponsorICA
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9386", value = "This is the ICA of entity that sponsors the owner of the ATM")

  public String getSponsorICA() {
    return sponsorICA;
  }


  public void setSponsorICA(String sponsorICA) {
    this.sponsorICA = sponsorICA;
  }


  public Atm supportsEmv(String supportsEmv) {
    
    this.supportsEmv = supportsEmv;
    return this;
  }

   /**
   * This indicates whether the ATM has the ability to read chip cards or not. Options are UNKNOWN, SUPPORTS_EMV, DOES_NOT_SUPPORT_EMV.
   * @return supportsEmv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "SUPPORTS_EMV", value = "This indicates whether the ATM has the ability to read chip cards or not. Options are UNKNOWN, SUPPORTS_EMV, DOES_NOT_SUPPORT_EMV.")

  public String getSupportsEmv() {
    return supportsEmv;
  }


  public void setSupportsEmv(String supportsEmv) {
    this.supportsEmv = supportsEmv;
  }


  public Atm surchargeFreeAllianceNetwork(String surchargeFreeAllianceNetwork) {
    
    this.surchargeFreeAllianceNetwork = surchargeFreeAllianceNetwork;
    return this;
  }

   /**
   * This value indicates whether or not the ATM participates in the MasterCard Shared (only) Surcharge Free Alliance network. Options are DOES_NOT_PARTICIPATE_IN_SFA, ALLPOINT_PREPAID, MONEYPASS_DEBIT, and ALL_SURCHARGE_FREE.
   * @return surchargeFreeAllianceNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DOES_NOT_PARTICIPATE_IN_SFA", value = "This value indicates whether or not the ATM participates in the MasterCard Shared (only) Surcharge Free Alliance network. Options are DOES_NOT_PARTICIPATE_IN_SFA, ALLPOINT_PREPAID, MONEYPASS_DEBIT, and ALL_SURCHARGE_FREE.")

  public String getSurchargeFreeAllianceNetwork() {
    return surchargeFreeAllianceNetwork;
  }


  public void setSurchargeFreeAllianceNetwork(String surchargeFreeAllianceNetwork) {
    this.surchargeFreeAllianceNetwork = surchargeFreeAllianceNetwork;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Atm atm = (Atm) o;
    return Objects.equals(this.accessFees, atm.accessFees) &&
        Objects.equals(this.addressLine1, atm.addressLine1) &&
        Objects.equals(this.addressLine2, atm.addressLine2) &&
        Objects.equals(this.airportCode, atm.airportCode) &&
        Objects.equals(this.atmTerminalId, atm.atmTerminalId) &&
        Objects.equals(this.availability, atm.availability) &&
        Objects.equals(this.camera, atm.camera) &&
        Objects.equals(this.countryCode, atm.countryCode) &&
        Objects.equals(this.countryName, atm.countryName) &&
        Objects.equals(this.countrySubdivisionCode, atm.countrySubdivisionCode) &&
        Objects.equals(this.countrySubdivisionName, atm.countrySubdivisionName) &&
        Objects.equals(this.city, atm.city) &&
        Objects.equals(this.distance, atm.distance) &&
        Objects.equals(this.distanceUnit, atm.distanceUnit) &&
        Objects.equals(this.geocodingResult, atm.geocodingResult) &&
        Objects.equals(this.handicapAccessible, atm.handicapAccessible) &&
        Objects.equals(this.hasSharedDeposit, atm.hasSharedDeposit) &&
        Objects.equals(this.isSurchargeFreeAlliance, atm.isSurchargeFreeAlliance) &&
        Objects.equals(this.latitude, atm.latitude) &&
        Objects.equals(this.locationName, atm.locationName) &&
        Objects.equals(this.locationType, atm.locationType) &&
        Objects.equals(this.longitude, atm.longitude) &&
        Objects.equals(this.owner, atm.owner) &&
        Objects.equals(this.ownerICA, atm.ownerICA) &&
        Objects.equals(this.postalCode, atm.postalCode) &&
        Objects.equals(this.routeTransactionNumber, atm.routeTransactionNumber) &&
        Objects.equals(this.sponsor, atm.sponsor) &&
        Objects.equals(this.sponsorICA, atm.sponsorICA) &&
        Objects.equals(this.supportsEmv, atm.supportsEmv) &&
        Objects.equals(this.surchargeFreeAllianceNetwork, atm.surchargeFreeAllianceNetwork);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessFees, addressLine1, addressLine2, airportCode, atmTerminalId, availability, camera, countryCode, countryName, countrySubdivisionCode, countrySubdivisionName, city, distance, distanceUnit, geocodingResult, handicapAccessible, hasSharedDeposit, isSurchargeFreeAlliance, latitude, locationName, locationType, longitude, owner, ownerICA, postalCode, routeTransactionNumber, sponsor, sponsorICA, supportsEmv, surchargeFreeAllianceNetwork);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Atm {\n");
    sb.append("    accessFees: ").append(toIndentedString(accessFees)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    airportCode: ").append(toIndentedString(airportCode)).append("\n");
    sb.append("    atmTerminalId: ").append(toIndentedString(atmTerminalId)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    camera: ").append(toIndentedString(camera)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    countrySubdivisionCode: ").append(toIndentedString(countrySubdivisionCode)).append("\n");
    sb.append("    countrySubdivisionName: ").append(toIndentedString(countrySubdivisionName)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    distanceUnit: ").append(toIndentedString(distanceUnit)).append("\n");
    sb.append("    geocodingResult: ").append(toIndentedString(geocodingResult)).append("\n");
    sb.append("    handicapAccessible: ").append(toIndentedString(handicapAccessible)).append("\n");
    sb.append("    hasSharedDeposit: ").append(toIndentedString(hasSharedDeposit)).append("\n");
    sb.append("    isSurchargeFreeAlliance: ").append(toIndentedString(isSurchargeFreeAlliance)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    locationName: ").append(toIndentedString(locationName)).append("\n");
    sb.append("    locationType: ").append(toIndentedString(locationType)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ownerICA: ").append(toIndentedString(ownerICA)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    routeTransactionNumber: ").append(toIndentedString(routeTransactionNumber)).append("\n");
    sb.append("    sponsor: ").append(toIndentedString(sponsor)).append("\n");
    sb.append("    sponsorICA: ").append(toIndentedString(sponsorICA)).append("\n");
    sb.append("    supportsEmv: ").append(toIndentedString(supportsEmv)).append("\n");
    sb.append("    surchargeFreeAllianceNetwork: ").append(toIndentedString(surchargeFreeAllianceNetwork)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

